args<- commandArgs(trailingOnly = TRUE)
library(ensembldb)
library(dplyr)
contig <- args[1]
print(paste0('Working on ',contig))
load('working_GRCm39.RData')
EDB<-EnsDb(DB)
df <- read.csv('good_region.bed',sep='\t',header=F)
working_contig_df <- df %>% filter(V1==contig)
grange_range <- makeGRangesFromDataFrame(working_contig_df,seqnames.field=c('V1'),start.field='V2',end.field='V3',strand.field='V6')
transcript_loc <- genomeToTranscript(grange_range,EDB)
write.csv(as.data.frame(transcript_loc),paste0('mES_MeRIP/tmp/tmp_',contig,'.csv'),quote=FALSE,row.names=FALSE)