args<- commandArgs(trailingOnly = TRUE)
library(ensembldb)
library(tplyr)
contig <- args[1]
print(paste0('Working on ',contig))
load('working.RData')
EDB<-EnsDb(DB)
df <- read.csv('hek293t_m6ace/m6ace_hek293t_GT_extend.csv')
working_contig_df <- df %>% filter(Chr==contig)
grange_range <- makeGRangesFromDataFrame(working_contig_df,seqnames.field=c('Chr'),start.field='Start',end.field='End',strand.field='Strand')
transcript_loc <- genomeToTranscript(grange_range,EDB)
write.csv(as.data.frame(transcript_loc),paste0('hek293t_m6ace/tmp/tmp_',contig,'.csv'),quote=FALSE,row.names=FALSE)