FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc g++ gffread && \
    pip install --no-cache-dir \
        'pandas<2.2' \
        'numpy<2' \
        'matplotlib==3.8.4' \
        openpyxl \
        'upsetplot==0.9.0' \
        'pyranges<1.0' \
        pysam \
        pyliftover && \
    apt-get purge -y gcc g++ && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /data
CMD ["python", "/data/analyze_groundtruth.py"]
