name: get the hek293t cell line m6ace-seq results

on:
  push:
    paths:
      - hek293t_m6ace/**
      - convert_genomic2transcriptomic.R
      - get_final_benchmark_hek293t.py
  release:
  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get merged
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install packges
        run: |
          pip install pandas
          mkdir bin/
          wget https://github.com/arq5x/bedtools2/releases/download/v2.31.0/bedtools.static -O bin/bedtools
          chmod +x bin/bedtools
      - name: Pull Down Needed docker image
        run: |
          docker pull btrspg/ensembldb:latest
      - name: Prepare the Needed data
        run: |
          wget https://ftp.ensembl.org/pub/release-104/gtf/homo_sapiens/Homo_sapiens.GRCh38.104.gtf.gz
          gzip -d Homo_sapiens.GRCh38.104.gtf.gz
      - name: Covert
        # if: ${{ hashFiles('hek293t_m6ace/Hek293T_m6aceSeq_results_annotated.csv') == '' }}
        run: |
          docker run --rm -w `pwd` -v `pwd`:`pwd` btrspg/ensembldb:latest bash -c "Rscript convert_genomic2transcriptomic.R"
      - name: Covert 2
        # if: ${{ hashFiles('hek293t_m6ace/Hek293T_m6aceSeq_annotated_m6aceincluded.bed') == '' }}
        run: |
          python get_final_benchmark_hek293t.py
      - name: Get Bed files
        # if: ${{ hashFiles('hek293t_m6ace/hek293t_m6ace/Hek293T.bed') == '' }}
        run: |
          ./bin/bedtools merge -i hek293t_m6ace/Hek293T_m6aceSeq_annotated_m6aceincluded.bed > hek293t_m6ace/Hek293T.bed
      - name: push to the remote
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add hek293t_m6ace ; git commit -m "`date`: convert to transcriptomic coordinates"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
